// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:dd33b0cd-c852-4041-b5de-f38263c73466",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_NnpjzuJeY",
    "aws_user_pools_web_client_id": "1ap3ku102aruev41anacu8173u",
    "oauth": {}
};


export default awsmobile;
